(import (builtin core)
        (sicp utils)
        (sicp utils set))

(define (count-pairs x)
  (define seen (make-set))
  (define (recurse x)
    (cond ((not (pair? x)) 0)
          ((seen 'contains x) 0)
          (else (seen 'insert x)
                (+ (recurse (car x))
                   (recurse (cdr x))
                   1))))
  (recurse x))


(define three '(1 2 3))
(define four (begin (define a (cons 1 '()))
                    (define b (cons 2 a))
                    (define c (cons a b))
                    c))
(define seven (begin (define a (cons 1 '()))
                     (define b (cons a a))
                     (define c (cons b b))
                     c))
(define infinite (begin (define a (cons 1 '()))
                        (define b (cons 2 a))
                        (define c (cons 3 b))
                        (set-cdr! a c)
                        c))

(println (count-pairs three) three)
(println (count-pairs four) four)
(println (count-pairs seven) seven)
(println (count-pairs infinite) "(1 2 3 1 2 3 1 2 ...)")
